//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalX.GUI.PH2.KyThuatVien
{
    using System.Drawing;
    using System.Globalization;
    using System.Resources;

    internal class KtvIcons
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal KtvIcons()
        {
        }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new ResourceManager(
                        "HospitalX.GUI.PH2.KyThuatVien.KtvIcons",
                        typeof(KtvIcons).Assembly);
                }

                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static Bitmap SidebarDashboardNormal
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarDashboardNormal", resourceCulture); }
        }

        internal static Bitmap SidebarDashboardActive
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarDashboardActive", resourceCulture); }
        }

        internal static Bitmap SidebarDichVuNormal
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarDichVuNormal", resourceCulture); }
        }

        internal static Bitmap SidebarDichVuActive
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarDichVuActive", resourceCulture); }
        }

        internal static Bitmap SidebarKetQuaNormal
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarKetQuaNormal", resourceCulture); }
        }

        internal static Bitmap SidebarKetQuaActive
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarKetQuaActive", resourceCulture); }
        }

        internal static Bitmap SidebarHoSoNormal
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarHoSoNormal", resourceCulture); }
        }

        internal static Bitmap SidebarHoSoActive
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarHoSoActive", resourceCulture); }
        }

        internal static Bitmap SidebarThongBaoNormal
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarThongBaoNormal", resourceCulture); }
        }

        internal static Bitmap SidebarThongBaoActive
        {
            get { return (Bitmap)ResourceManager.GetObject("SidebarThongBaoActive", resourceCulture); }
        }
    }
}
